---
title: "Downtown Commutes"
author: "Reuven Herzog"
date: "2/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load libraries, results = false}
library(lehdr)
library(tidycensus)
library(tidyverse)
library(units)
library(sf)
library(knitr)
library(PNWColors)
library(here)
```

```{r lodes wac data, message = FALSE}

#specify MSA tracts
MSA <- get_acs(geography = "tract", state = "TX", variables = "B19001_001",county = c("Travis","Bastrop","Caldwell","Hays","Williamson"), geometry = TRUE)
MSA_GEOIDS <- MSA$GEOID

# #get Origin-Destination data for the cordoned census tracts
# #austin, tx, tracts 7 and 11
# #hahaha slurpees
# lodes <- grab_lodes(state = "tx", year = 2019, lodes_type = "od", job_type = "JT00",
#            segment = "S000", state_part = "main", agg_geo = "tract") %>%
#   filter(w_tract %in% c("48453001100","48453000700"), h_tract %in% MSA_GEOIDS)
  
```

```{r import lodes and MSA geoids}
MSA_GEOIDS <- read_csv(here("MSA GEOIDs.csv"),col_types = "c")
lodes <- read_csv(here("O-D commutes all MSA.csv"), col_types = "ncccnnnnnnnnnn")
```



```{r aggregate}
commute_origin <- lodes %>%
  select(w_tract, h_tract, S000) %>%
  group_by(h_tract) %>%
  rename(GEOID = h_tract) %>%
  summarize(commutes = sum(S000))
```

```{r join}
MSA <- left_join(MSA, commute_origin)
```

```{r make downtown polygon}
downtown <- st_union(filter(MSA,GEOID == "48453001100"),
                     filter(MSA,GEOID == "48453000700"))
```


```{r visualize commutes}
commute_dens_map <- ggplot(MSA) +
  geom_sf(aes(fill = as.numeric(commutes)), color = NA) +
  scale_fill_viridis_c(name = "Commuters to Downtown\nby Census Tract")

commute_dens_map
```

```{r the downtown moat}
moat_map <- ggplot(MSA) +
  geom_sf(aes(color = NULL))+
  geom_sf(data = downtown, color = 'red', lwd = 1)

moat_map
```

```{r}
downtown1 <- left_join(downtown, zones)
```




```{r find primary employment type}
prim_emp <- function(basic, retail, service) {
  if((basic >= retail) & (basic >= service))
    return("basic")
  else if(retail >= service)
    return("retail")
  else return("service")
}

zones <- zones %>%
  mutate(primary_emp_type = prim_emp(basic_emp, retail_emp, service_emp)
  )

```

