---
title: "Preparing data for travel skims"
author: "Reuven Herzog"
date: "2/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## script overview

In this document we load the OpenStreetMap data and the GTFS data for the Austin MSA.
Then prepare the OSM data for editing.

We also create a file of centroids for the travel skims.

Actually creating the travel skims will be done in a separate file.

```{r load libraries}
library(sf)
library(tigris)
library(tidyverse)
library(osmdata)
library(scenRios)
library(here)
```

OSM-related code blocks commented out to avoid wasting our time by accidentally running them

```{r pull OSM data}
# # Try to avoid re-running this one, because the query takes a few minutes
# # to execute
# 
# # Load the MSA boundaries
# boundary <- core_based_statistical_areas() %>%
#   filter(GEOID == "12420")
# 
# # Define a bounding box containing the MSA
# austin_bbox <- st_bbox(boundary)
# 
# q <- opq(bbox = austin_bbox, timeout = 120) %>% # create a query
#   add_osm_feature(key = 'highway') %>% # request only road data
#   osmdata_xml(file = 'existing/networks/streets.osm') # download osm file
```

```{r prepare Alternate OSM map}
# # Creates a copy of the "existing" OSM map, prepares it for editing in JSOM,
# # and outputs it to the "alternative" folder
# 
# old_network <- read_lines(here("existing",
#                                "networks", 
#                                "streets.osm"))
# 
# new_network <- osm_prep_network(old_network)
# 
# write_lines(new_network,
#             file = here("alternative",
#                         "networks",
#                         "streets.osm"))
```

```{r pull GTFS data}
# Actually we downloaded it externally via OpenMobilityData, it is saved in
# existing/network and copied into alternative/network
```

```{r make centroids}
centroids <- here("zones",
                  "boundaries.geojson") %>%
  st_read() %>%
  st_centroid() %>%
  st_transform("WGS84") %>%
  rename(id = GEOID)

st_write(centroids, here("zones", "centroids.geojson"))
```