---
title: "Assignment 7"
author: "Reuven Herzog"
date: "3/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
library(here)
library(tidyverse)
library(survey)
library(srvyr)
library(naniar)
library(jtools)
library(knitr)
```


First we need to bring in our National Household Travel Survey data.
(Obtained from https://nhts.ornl.gov/)

We already filtered the complete dataset to only Austin data, so it could
fit on our Github repo.
(See adjacent "A7 get only austin data.rmd")

```{r bring in NHTS data}
austin_trips <- read_csv(here(
                        "assignment rmd docs",
                        "a7",
                        "austin_trips.csv"))

austin_hhs <- read_csv(here(
                      "assignment rmd docs",
                      "a7",
                      "austin_hhs.csv"))
```

Code blocks copied from skills page - need to adapt for Austin

```{r}
austin_hhs <- austin_hhs %>%
  mutate(inc_quint_ = case_when(HHFAMINC == "01" ~ "1st",
                               HHFAMINC == "02" ~ "1st",
                               HHFAMINC == "03" ~ "1st",
                               HHFAMINC == "04" ~ "2nd",
                               HHFAMINC == "05" ~ "2nd",
                               HHFAMINC == "06" ~ "3rd",
                               HHFAMINC == "07" ~ "4th",
                               HHFAMINC == "08" ~ "5th",
                               HHFAMINC == "09" ~ "5th",
                               HHFAMINC == "10" ~ "5th",
                               HHFAMINC == "11" ~ "5th",
                               TRUE ~ "NA")) %>%
  mutate(size_ = case_when(HHSIZE == 1 ~ "one",
                              HHSIZE == 2 ~ "two",
                              HHSIZE == 3 ~ "three",
                              TRUE ~ "four_plus")) %>%
  mutate(zero_veh_ = (HHVEHCNT == 0)) %>%
  replace_with_na(list(inc_quint_ = "NA")) %>%
  select(HOUSEID, zero_veh_, size_, inc_quint_, WTHHFIN) 
```

```{r}
trips_by_purpose <- austin_trips %>%
  select(HOUSEID, WHYFROM, WHYTO) %>%
  mutate(home_based = case_when(WHYTO == "01" ~ TRUE,
                                WHYTO == "02" ~ TRUE,
                                WHYFROM == "01" ~ TRUE,
                                WHYFROM == "02" ~ TRUE,
                                TRUE ~ FALSE)) 

trips_by_purpose <- trips_by_purpose %>%
  mutate(work = ifelse(WHYTO == "03" | WHYFROM == "03", TRUE, FALSE)) %>%
  mutate(purpose = case_when(home_based & work ~ "HBW",
                            home_based ~ "HBO",
                            TRUE ~ "NHB")) %>%
  group_by(HOUSEID, purpose)

trips_by_purpose <- trips_by_purpose %>%
  summarize(n = n()) %>%
  pivot_wider(names_from = "purpose", values_from = "n") 
```

```{r}
hh_trips <- left_join(buffalo_hhs, trips_by_purpose) %>%
  replace_na(list(HBW = 0,
                  HBO = 0,
                  NHB = 0))
```

```{r}
svy_trips <- hh_trips %>%
  as_survey(weights = WTHHFIN)
```

```{r}
HBO_model1 <- svyglm(HBO ~ zero_veh_ + size_ + inc_quint_, svy_trips)

export_summs(HBO_model1, 
             error_pos = "right", 
             error_format = "(p = {p.value})",
             model.names = "Full model")
```